### ISSUE TITLE
Working Example

### ISSUE THREAD

**Issue by raunaq-m** [raunaq-m/MLEHaplo#1]
Create a working example and a wrapper script so that the code can be run easily.

**Comment by sdwfrost** [comment]
This would be great; as you can see from [here](https://gist.github.com/sdwfrost/14c4579e7909d8b391769c1961abadea), I can get through all the steps, until the MLE.

I've checked the files, and they all (to my naive eyes) look as they should. Many of the scripts don't complain if they don't find the filename, so early on I had made some mistakes that resulted in empty files.

**Comment by raunaq-m** [comment]
Hi @sdwfrost , I will be happy to look at why it is not working. Would it be possible for you to share with me the files that are used as input for the MLEHaplo step. The final script uses two intermediate files that are generated by dg_cover.pl script. I would be happy to look at the files and talk to you about them.

**Comment by raunaq-m** [comment]
A Working Example with temporary files and all steps is uploaded now in the Example Directory. Please download New Release of the software for example and some minor changes in the code.
